# Generated by Django 3.2.7 on 2021-10-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_books'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cat', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quant', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
