# Generated by Django 3.2.7 on 2021-10-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cbse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
