# Generated by Django 3.2.7 on 2021-10-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_fibuy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fibuy',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
