# Generated by Django 3.2.7 on 2021-10-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_phone_no_fibuy_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('money', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('cate', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
