# Generated by Django 3.2.7 on 2021-10-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_sell'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cbse',
        ),
        migrations.DeleteModel(
            name='Defence',
        ),
        migrations.DeleteModel(
            name='Engg',
        ),
        migrations.DeleteModel(
            name='Icse',
        ),
        migrations.DeleteModel(
            name='Jee',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
