# Generated by Django 3.2.7 on 2021-10-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20211022_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='fibuy',
            name='prod_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
